services:
  uptime-kuma:
    build:
      context: .
      dockerfile: docker/dockerfile
      target: release
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - /opt/uptime-kuma/data:/app/data
    ports:
      - "3001:3001"
